version: "2.3"
services:
  app:
    build:
      context: ./docker/images/node
      dockerfile: Dockerfile
    expose:
      - 3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      main:
        ipv4_address: 10.110.0.2
    restart: "always"

  redoc:
    image: redocly/redoc:latest
    volumes:
      - $PWD/storage/tmp/swagger.json:/usr/share/nginx/html/swagger.json
    environment:
      - SPEC_URL=swagger.json
    ports:
      - 4000:80
    networks:
      main:
        ipv4_address: 10.110.0.3
    restart: "always"

  postgres:
    image: postgres:11.10
    volumes:
      - ${PG_DIR_DATA:-postgres-storage}:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - $PWD/storage/docker/volume/postgres-migration/:/docker-entrypoint-initdb.d/
    networks:
      main:
        ipv4_address: 10.110.0.4
    restart: "always"

  redis:
    image: redis:7.0.4-alpine3.16
    volumes:
      - ${REDIS_DIR_DATA:-redis-storage}:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      main:
        ipv4_address: 10.110.0.5
    restart: "always"

  build-myst-image:
    build:
      context: ./docker/images/myst
      dockerfile: Dockerfile
    image: myst-service:latest
    network_mode: "bridge"
    restart: "no"
    entrypoint: ""
    command: /bin/bash -c "sleep 1; exit"

  build-myst-connect-image:
    build:
      context: ./docker/images/myst-connect
      dockerfile: Dockerfile
    image: myst-connect-service:latest
    network_mode: "bridge"
    restart: "no"
    entrypoint: ""
    command: /bin/bash -c "sleep 1; exit"

volumes:
  postgres-storage: { }
  redis-storage: { }

networks:
  main:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.110.0.0/20
          gateway: 10.110.0.1
