export enum ExceptionEnum {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  NOT_FOUND_USER_ERROR = 'NOT_FOUND_USER',
  EXIST_ERROR = 'EXIST_ERROR',
  MODEL_ID_NOT_EXIST_ERROR = 'MODEL_ID_NOT_EXIST_ERROR',
  REPOSITORY_ERROR = 'REPOSITORY_ERROR',
  AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR',
}
