export enum ProviderTokenEnum {
  IDENTIFIER_UUID = 'IDENTIFIER_UUID',
  IDENTIFIER_UUID_NULL = 'IDENTIFIER_UUID_NULL',
  DATE_TIME_DEFAULT = 'DATE_TIME_DEFAULT',

  USER_SERVICE_DEFAULT = 'USER_SERVICE',
  AUTH_SERVICE_DEFAULT = 'AUTH_SERVICE_DEFAULT',

  USER_PG_REPOSITORY = 'USER_PG_REPOSITORY',
  USERS_SQUID_FILE_REPOSITORY = 'USERS_SQUID_FILE_REPOSITORY',
}
