export enum ProviderTokenEnum {
  IDENTIFIER_UUID = 'IDENTIFIER_UUID',
  IDENTIFIER_UUID_NULL = 'IDENTIFIER_UUID_NULL',
  DATE_TIME_DEFAULT = 'DATE_TIME_DEFAULT',

  USER_SERVICE_DEFAULT = 'USER_SERVICE',
  AUTH_SERVICE_DEFAULT = 'AUTH_SERVICE_DEFAULT',
  RUNNER_SERVICE_DOCKER = 'RUNNER_SERVICE_DOCKER',

  USER_PG_REPOSITORY = 'USER_PG_REPOSITORY',

  MYST_IDENTITY_PG_REPOSITORY = 'MYST_IDENTITY_PG_REPOSITORY',
  MYST_IDENTITY_FILE_REPOSITORY = 'MYST_IDENTITY_FILE_REPOSITORY',

  USERS_SQUID_FILE_REPOSITORY = 'USERS_SQUID_FILE_REPOSITORY',

  MYST_API_REPOSITORY = 'MYST_API_REPOSITORY',
  MYST_CACHE_ID_API_REPOSITORY = 'MYST_CACHE_ID_API_REPOSITORY',
  MYST_AGGREGATE_REPOSITORY = 'MYST_AGGREGATE_REPOSITORY',

  DOCKER_RUNNER_REPOSITORY = 'DOCKER_RUNNER_REPOSITORY',

  SYSTEM_INFO_REPOSITORY = 'SYSTEM_INFO_REPOSITORY',
}
