FROM node:16.16.0-alpine3.16 AS build

RUN apk add --no-cache apache2-utils curl su-exec; \
    mkdir -p /data /data/src /data/storage/tmp; \
    chown -R node:node /data

WORKDIR /data

COPY --chown=node:node \
        tsconfig*.json \
        package.json \
        nest-cli.json \
        ./

RUN npm install

COPY --chown=node:node \
        src/ \
        ./src

VOLUME /data/storage/tmp

COPY docker-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
